/* ==========================================================================
   knotsocutepk — cart, drawer, and money formatting.
   Loaded on every page. Depends on catalogue.js (generated by build.js).

   Do not edit the catalogue here. Edit products.json.
   ========================================================================== */
(function () {
  'use strict';

  const C = window.KSC_CATALOGUE || { products: [], settings: {} };
  const KEY = 'ksc_cart_v1';
  const MAX_QTY = 20;

  document.documentElement.classList.add('has-js');

  /* ---------------- money: the one shared formatter ------------------ */
  const money = (n) => 'PKR ' + Number(n || 0).toLocaleString('en-PK');
  window.KSCmoney = money;

  /* ---------------- catalogue lookup --------------------------------- */
  const bySlug = {};
  C.products.forEach(function (p) { bySlug[p.slug] = p; });

  /* ---------------- cart state -------------------------------------- */
  function read() {
    try {
      const raw = JSON.parse(localStorage.getItem(KEY) || '[]');
      if (!Array.isArray(raw)) return [];
      // Drop anything that no longer exists in the catalogue, so a deleted
      // product can't wedge the cart or reach checkout.
      return raw.filter(function (l) {
        return l && bySlug[l.slug] && Number(l.qty) > 0;
      }).map(function (l) {
        return {
          slug: String(l.slug),
          colourway: l.colourway ? String(l.colourway) : '',
          qty: Math.min(MAX_QTY, Math.max(1, parseInt(l.qty, 10) || 1))
        };
      });
    } catch (e) { return []; }
  }

  function write(lines) {
    try { localStorage.setItem(KEY, JSON.stringify(lines)); } catch (e) {}
    paint();
    document.dispatchEvent(new CustomEvent('ksc:cart', { detail: lines }));
  }

  const idOf = (slug, colourway) => slug + '|' + (colourway || '');

  const Cart = {
    lines: read,

    count: function () {
      return read().reduce(function (n, l) { return n + l.qty; }, 0);
    },

    /* Detailed lines with catalogue data joined in. */
    detailed: function () {
      return read().map(function (l) {
        const p = bySlug[l.slug];
        return {
          slug: l.slug,
          colourway: l.colourway,
          qty: l.qty,
          name: p.name,
          tag: p.tag,
          price: p.price,
          lineTotal: p.price * l.qty,
          image: (p.images && p.images[0]) || null,
          href: '/shop/' + l.slug
        };
      });
    },

    subtotal: function () {
      return this.detailed().reduce(function (n, l) { return n + l.lineTotal; }, 0);
    },

    /* Delivery is quoted from the city, and re-verified server side. */
    delivery: function (city) {
      const d = (C.settings && C.settings.delivery) || {};
      const sub = this.subtotal();
      if (!sub) return 0;
      if (d.freeOver && sub >= d.freeOver) return 0;
      const isLahore = String(city || '').trim().toLowerCase() === 'lahore';
      return isLahore ? (d.lahore || 0) : (d.restOfPakistan || 0);
    },

    total: function (city) { return this.subtotal() + this.delivery(city); },

    add: function (slug, colourway, qty) {
      const p = bySlug[slug];
      if (!p || p.available === false) return false;
      // A product with colourways must have one chosen.
      if (p.colourways && p.colourways.length && !colourway) return false;

      const lines = read();
      const id = idOf(slug, colourway);
      const hit = lines.find(function (l) { return idOf(l.slug, l.colourway) === id; });
      const n = Math.max(1, parseInt(qty, 10) || 1);

      if (hit) hit.qty = Math.min(MAX_QTY, hit.qty + n);
      else lines.push({ slug: slug, colourway: colourway || '', qty: Math.min(MAX_QTY, n) });

      write(lines);
      return true;
    },

    setQty: function (slug, colourway, qty) {
      const id = idOf(slug, colourway);
      let lines = read();
      const n = parseInt(qty, 10) || 0;
      if (n <= 0) {
        lines = lines.filter(function (l) { return idOf(l.slug, l.colourway) !== id; });
      } else {
        const hit = lines.find(function (l) { return idOf(l.slug, l.colourway) === id; });
        if (hit) hit.qty = Math.min(MAX_QTY, n);
      }
      write(lines);
    },

    remove: function (slug, colourway) { this.setQty(slug, colourway, 0); },

    clear: function () { write([]); }
  };
  window.KSCcart = Cart;

  /* ---------------- header badge ------------------------------------ */
  function paint() {
    const n = Cart.count();
    document.querySelectorAll('[data-cart-count]').forEach(function (el) {
      const was = el.textContent;
      el.textContent = n;
      el.setAttribute('data-empty', n === 0 ? '1' : '0');
      if (was !== String(n) && n > 0) {
        el.classList.add('bump');
        setTimeout(function () { el.classList.remove('bump'); }, 350);
      }
    });
    document.querySelectorAll('[data-cart-label]').forEach(function (el) {
      el.setAttribute('aria-label', n === 1 ? 'Cart, 1 item' : 'Cart, ' + n + ' items');
    });
    if (drawerEl && drawerEl.classList.contains('open')) fillDrawer();
  }

  /* ---------------- drawer ------------------------------------------ */
  let veilEl = null, drawerEl = null, lastFocus = null;

  function buildDrawer() {
    if (drawerEl) return;

    veilEl = document.createElement('div');
    veilEl.className = 'drawer-veil';
    veilEl.hidden = true;
    veilEl.addEventListener('click', closeDrawer);

    drawerEl = document.createElement('aside');
    drawerEl.className = 'drawer';
    drawerEl.setAttribute('role', 'dialog');
    drawerEl.setAttribute('aria-modal', 'true');
    drawerEl.setAttribute('aria-label', 'Your cart');
    drawerEl.hidden = true;
    drawerEl.innerHTML =
      '<div class="drawer-top">' +
        '<h2>your cart</h2>' +
        '<button class="drawer-x" type="button" aria-label="Close cart">&times;</button>' +
      '</div>' +
      '<div class="drawer-body" data-drawer-body></div>' +
      '<div class="drawer-foot" data-drawer-foot></div>';

    document.body.appendChild(veilEl);
    document.body.appendChild(drawerEl);

    drawerEl.querySelector('.drawer-x').addEventListener('click', closeDrawer);

    // Delegated controls
    drawerEl.addEventListener('click', function (e) {
      const b = e.target.closest('[data-act]');
      if (!b) return;
      const slug = b.dataset.slug, cw = b.dataset.cw || '';
      const cur = read().find(function (l) { return idOf(l.slug, l.colourway) === idOf(slug, cw); });
      if (!cur) return;
      if (b.dataset.act === 'inc') Cart.setQty(slug, cw, cur.qty + 1);
      if (b.dataset.act === 'dec') Cart.setQty(slug, cw, cur.qty - 1);
      if (b.dataset.act === 'rm')  Cart.remove(slug, cw);
      announce();
    });
  }

  function fillDrawer() {
    const body = drawerEl.querySelector('[data-drawer-body]');
    const foot = drawerEl.querySelector('[data-drawer-foot]');
    const lines = Cart.detailed();

    if (!lines.length) {
      body.innerHTML =
        '<div class="empty"><div class="big">nothing in here yet.</div>' +
        '<p>Every piece is made to order, one at a time.</p></div>';
      foot.innerHTML = '<a class="btn-add" href="/shop" style="text-align:center;' +
        'text-decoration:none;display:block">Browse the pieces</a>';
      return;
    }

    body.innerHTML = lines.map(function (l) {
      const img = l.image
        ? '<div class="line-shot"><img src="/' + l.image.src + '" alt="" loading="lazy"></div>'
        : '<div class="line-shot"></div>';
      return '<div class="line">' + img +
        '<div>' +
          '<a class="line-name" href="' + l.href + '">' + esc(l.name) + '</a>' +
          (l.colourway ? '<div class="line-var">' + esc(l.colourway) + '</div>' : '') +
          '<div class="line-price">' + money(l.price) + ' each</div>' +
          '<div class="line-qty">' +
            '<button type="button" data-act="dec" data-slug="' + l.slug + '" data-cw="' +
              esc(l.colourway) + '" aria-label="Reduce quantity of ' + esc(l.name) + '"' +
              (l.qty <= 1 ? '' : '') + '>&minus;</button>' +
            '<span class="n">' + l.qty + '</span>' +
            '<button type="button" data-act="inc" data-slug="' + l.slug + '" data-cw="' +
              esc(l.colourway) + '" aria-label="Increase quantity of ' + esc(l.name) + '"' +
              (l.qty >= MAX_QTY ? ' disabled' : '') + '>+</button>' +
            '<button class="line-rm" type="button" data-act="rm" data-slug="' + l.slug +
              '" data-cw="' + esc(l.colourway) + '">Remove</button>' +
          '</div>' +
        '</div>' +
        '<div class="line-price">' + money(l.lineTotal) + '</div>' +
      '</div>';
    }).join('');

    foot.innerHTML =
      '<div class="row"><span>Subtotal</span><span>' + money(Cart.subtotal()) + '</span></div>' +
      '<div class="drawer-note">Delivery is added at checkout, once we know your city.</div>' +
      '<a class="btn-add" href="/checkout" style="text-align:center;text-decoration:none;' +
        'display:block">Checkout</a>' +
      '<a href="/shop" style="text-align:center;font-size:11px;letter-spacing:.2em;' +
        'text-transform:uppercase;color:var(--muted-2)">Keep shopping</a>';
  }

  function openDrawer() {
    buildDrawer();
    lastFocus = document.activeElement;
    veilEl.hidden = false;
    drawerEl.hidden = false;
    fillDrawer();
    // Force a reflow so the transition has a start value to animate from.
    // requestAnimationFrame would be the obvious choice, but it is starved
    // whenever the page is not compositing (background tab), which would
    // leave the drawer mounted but never slid into view.
    void veilEl.offsetWidth;
    void drawerEl.offsetWidth;
    veilEl.classList.add('open');
    drawerEl.classList.add('open');
    document.body.classList.add('is-locked');
    drawerEl.querySelector('.drawer-x').focus();
    document.addEventListener('keydown', onKey);
  }

  function closeDrawer() {
    if (!drawerEl) return;
    veilEl.classList.remove('open');
    drawerEl.classList.remove('open');
    document.body.classList.remove('is-locked');
    document.removeEventListener('keydown', onKey);
    setTimeout(function () { veilEl.hidden = true; drawerEl.hidden = true; }, 480);
    if (lastFocus && lastFocus.focus) lastFocus.focus();
  }

  // Escape closes; Tab is trapped inside the drawer.
  function onKey(e) {
    if (e.key === 'Escape') { closeDrawer(); return; }
    if (e.key !== 'Tab') return;
    const f = drawerEl.querySelectorAll(
      'a[href],button:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])');
    if (!f.length) return;
    const first = f[0], last = f[f.length - 1];
    if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
    else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
  }

  window.KSCdrawer = { open: openDrawer, close: closeDrawer };

  /* ---------------- aria-live announcements ------------------------- */
  let liveEl = null;
  function announce(msg) {
    if (!liveEl) {
      liveEl = document.createElement('div');
      liveEl.className = 'vh';
      liveEl.setAttribute('role', 'status');
      liveEl.setAttribute('aria-live', 'polite');
      document.body.appendChild(liveEl);
    }
    const n = Cart.count();
    liveEl.textContent = msg || ('Cart updated. ' + n + (n === 1 ? ' item' : ' items') +
      ', subtotal ' + money(Cart.subtotal()) + '.');
  }
  window.KSCannounce = announce;

  /* ---------------- wiring ------------------------------------------ */
  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  window.KSCesc = esc;

  document.addEventListener('click', function (e) {
    const open = e.target.closest('[data-open-cart]');
    if (open) { e.preventDefault(); openDrawer(); }
  });

  // Another tab changed the cart — resync.
  window.addEventListener('storage', function (e) { if (e.key === KEY) paint(); });

  /* ---------------- reveal on scroll (all pages) --------------------- */
  const targets = document.querySelectorAll('.reveal, .wipe');
  if (!('IntersectionObserver' in window)) {
    targets.forEach(function (el) { el.classList.add('in'); });
  } else {
    const io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) { en.target.classList.add('in'); io.unobserve(en.target); }
      });
    }, { rootMargin: '0px 0px -12% 0px', threshold: 0.12 });
    targets.forEach(function (el) { io.observe(el); });
  }

  /* ---------------- scroll progress bar ----------------------------- */
  const bar = document.getElementById('progress');
  if (bar) {
    let queued = false;
    const draw = function () {
      const h = document.documentElement.scrollHeight - window.innerHeight;
      bar.style.transform = 'scaleX(' + (h > 0 ? window.scrollY / h : 0) + ')';
      queued = false;
    };
    addEventListener('scroll', function () {
      if (!queued) { queued = true; requestAnimationFrame(draw); }
    }, { passive: true });
    draw();
  }

  paint();
})();
